# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    # When the workflow runs, this is the name that is logged
    # This job will run three times, once for each "os" defined
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/master' }}
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore Nuget Packages
      run: nuget restore WIK.ServiceOrderMES.sln
      
    - name: Build the Solution
      run: msbuild WIK.ServiceOrderMES.sln /p:Configuration=Release
